name: CarbonMC
version: 1.0
author: CarbonMC
main: io.github.carbon.carbonmc.plugin.PaperLoader
depend: [NoteBlockAPI]
api-version: 1.19
softdepend: [PlaceholderAPI]
commands:
  npc:
  music:
    permission: carbon.command.music
  adminmusic:
    permission: carbon.command.adminmusic
  carbon: